#!/usr/bin/env bash
#
# generate-license-inventory.sh — regenerate docs/dependency-licenses.md from a curated
# license map, and verify that map still covers the real distributable dependency closure
# of the shipped app (src/Nuvio.Desktop, --include-transitive).
#
# We curate licenses (rather than trusting whatever a tool scrapes) because the inventory
# is a release-blocking legal artifact and must never contain "TBD". The dotnet list pass
# guards against silent drift: if a new package enters the graph that the curated map does
# not recognise, this script fails so the map is updated before release.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/docs/dependency-licenses.md"
SHIPPED_PROJECT="$REPO_ROOT/src/Nuvio.Desktop/Nuvio.Desktop.csproj"

# Curated coverage prefixes for the distributable closure. Every package id reported by
# `dotnet list` for the shipped project must match one of these, otherwise the curated
# table below is stale and the run fails.
KNOWN_PREFIXES=(
  "Avalonia"
  "AvaloniaUI.DiagnosticsSupport"
  "CommunityToolkit.Mvvm"
  "HarfBuzzSharp"
  "MicroCom.Runtime"
  "Microsoft.Data.Sqlite"
  "Microsoft.Extensions."
  "Microsoft.IO.RecyclableMemoryStream"
  "SkiaSharp"
  "SQLitePCLRaw."
  "Tmds.DBus"
)

echo "Scanning distributable dependency closure of src/Nuvio.Desktop ..."
LIST_OUTPUT="$(dotnet list "$SHIPPED_PROJECT" package --include-transitive 2>/dev/null || true)"

if [ -n "$LIST_OUTPUT" ]; then
  # Package ids are the second token on lines whose first non-space token is '>'.
  PACKAGE_IDS="$(printf '%s\n' "$LIST_OUTPUT" | awk '$1 == ">" {print $2}' | sort -u)"
  MISSING=0
  while IFS= read -r pkg; do
    [ -z "$pkg" ] && continue
    matched=0
    for prefix in "${KNOWN_PREFIXES[@]}"; do
      case "$pkg" in
        "$prefix"*) matched=1; break ;;
      esac
    done
    if [ "$matched" -eq 0 ]; then
      echo "  UNCOVERED package in graph (update curated map): $pkg" >&2
      MISSING=1
    fi
  done <<< "$PACKAGE_IDS"
  if [ "$MISSING" -ne 0 ]; then
    echo "generate-license-inventory: dependency graph changed; curated license map is incomplete." >&2
    exit 1
  fi
  echo "  All graph packages are covered by the curated license map."
else
  echo "  WARNING: 'dotnet list' produced no output (offline / SDK mismatch); emitting curated table without graph verification." >&2
fi

cat > "$OUT" <<'EOF'
# Dependency License Inventory

Generated by `scripts/generate-license-inventory.{sh,ps1}`. Do not hand-edit: re-run the
generator after changing dependencies. The generator fails if a new package enters the
shipped dependency graph (`src/Nuvio.Desktop`, transitive) without a curated license, so
this table never carries an unresolved placeholder; every row names a concrete license.

"Bundled" means the component ships inside the release artifact. The app is published
`--self-contained` per RID, so the .NET runtime and the Avalonia/Skia/SQLite native
assets for the target RID are bundled. mpv/libmpv is **not** bundled — see
[`native-dependency-provenance.md`](native-dependency-provenance.md).

| Dependency | Purpose | License | Bundled | Source / Notes |
|---|---|---|---|---|
| .NET runtime (`Microsoft.NETCore.App`) | application runtime | MIT | yes | https://github.com/dotnet/runtime — self-contained per-RID publish |
| Avalonia (`Avalonia.*`, incl. Desktop/Skia/Native/Win32/X11/FreeDesktop/HarfBuzz/Remote.Protocol/BuildServices) | desktop UI framework | MIT | yes | https://github.com/AvaloniaUI/Avalonia — bundled ANGLE natives (`Avalonia.Angle.Windows.Natives`) are BSD-3-Clause |
| Inter (font, via `Avalonia.Fonts.Inter`) | bundled UI font | SIL OFL 1.1 | yes | https://github.com/rsms/inter |
| SkiaSharp (`SkiaSharp`, `SkiaSharp.NativeAssets.*`) | 2D rendering backend (Avalonia.Skia) | MIT | yes | https://github.com/mono/SkiaSharp — native Skia engine is BSD-3-Clause |
| HarfBuzzSharp (`HarfBuzzSharp`, `HarfBuzzSharp.NativeAssets.*`) | text shaping | MIT | yes | https://github.com/mono/SkiaSharp |
| MicroCom.Runtime | COM interop runtime used by Avalonia | MIT | yes | https://github.com/AvaloniaUI/MicroCom |
| CommunityToolkit.Mvvm | MVVM helpers | MIT | yes | https://github.com/CommunityToolkit/dotnet |
| Microsoft.Data.Sqlite (`.Core`) | SQLite ADO.NET provider | MIT | yes | https://github.com/dotnet/efcore |
| SQLitePCLRaw (`SQLitePCLRaw.*`) | native SQLite bindings (`e_sqlite3`) | Apache-2.0 | yes | https://github.com/ericsink/SQLitePCL.raw — the bundled SQLite engine itself is public domain |
| Microsoft.Extensions.* (`DependencyInjection.Abstractions`, `Logging.Abstractions`) | abstractions pulled in by dependencies | MIT | yes | https://github.com/dotnet/runtime |
| Microsoft.IO.RecyclableMemoryStream | pooled memory streams | MIT | yes | https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream |
| Tmds.DBus.Protocol | Linux D-Bus integration (Avalonia.FreeDesktop) | MIT | yes | https://github.com/tmds/Tmds.DBus |
| AvaloniaUI.DiagnosticsSupport | developer diagnostics overlay | MIT | no | https://github.com/AvaloniaUI/Avalonia — Debug-only; excluded from Release artifacts |
| mpv / libmpv | playback backend | GPL-2.0-or-later / LGPL-2.1-or-later | no | External: discovered and launched, never bundled. See `native-dependency-provenance.md` |
| MPV Manager | optional setup helper | MIT per upstream site | no | Documented only; not launched, bundled, or trusted as a playback executable |

## Source availability

GPL source-availability obligations for these binaries are satisfied by the written
offer and source tarball described in [`source-availability.md`](source-availability.md).
EOF

echo "Wrote $OUT"
if grep -q 'TBD' "$OUT"; then
  echo "generate-license-inventory: TBD found in generated inventory." >&2
  exit 1
fi
echo "No TBD rows remain."
