<#
.SYNOPSIS
  Regenerate docs/dependency-licenses.md from a curated license map and verify the map
  still covers the distributable dependency closure of the shipped app.
.DESCRIPTION
  Curated (rather than scraped) because the inventory is a release-blocking legal artifact
  that must never contain "TBD". The dotnet list pass guards against silent drift: a new
  package in the graph that the curated map does not recognise fails the run.
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$out = Join-Path $repoRoot 'docs/dependency-licenses.md'
$shippedProject = Join-Path $repoRoot 'src/Nuvio.Desktop/Nuvio.Desktop.csproj'

# Curated coverage prefixes for the distributable closure.
$knownPrefixes = @(
    'Avalonia',
    'AvaloniaUI.DiagnosticsSupport',
    'CommunityToolkit.Mvvm',
    'HarfBuzzSharp',
    'MicroCom.Runtime',
    'Microsoft.Data.Sqlite',
    'Microsoft.Extensions.',
    'Microsoft.IO.RecyclableMemoryStream',
    'SkiaSharp',
    'SQLitePCLRaw.',
    'Tmds.DBus'
)

Write-Host 'Scanning distributable dependency closure of src/Nuvio.Desktop ...'
$listOutput = & dotnet list $shippedProject package --include-transitive 2>$null

if ($LASTEXITCODE -eq 0 -and $listOutput) {
    $packageIds = $listOutput |
        Where-Object { $_ -match '^\s*>\s+(\S+)' } |
        ForEach-Object { ($_ -split '\s+' | Where-Object { $_ -ne '' })[1] } |
        Sort-Object -Unique
    $missing = $false
    foreach ($pkg in $packageIds) {
        $matched = $false
        foreach ($prefix in $knownPrefixes) {
            if ($pkg.StartsWith($prefix)) { $matched = $true; break }
        }
        if (-not $matched) {
            Write-Error "UNCOVERED package in graph (update curated map): $pkg" -ErrorAction Continue
            $missing = $true
        }
    }
    if ($missing) {
        throw 'generate-license-inventory: dependency graph changed; curated license map is incomplete.'
    }
    Write-Host '  All graph packages are covered by the curated license map.'
}
else {
    Write-Warning 'dotnet list produced no output (offline / SDK mismatch); emitting curated table without graph verification.'
}

$content = @'
# Dependency License Inventory

Generated by `scripts/generate-license-inventory.{sh,ps1}`. Do not hand-edit: re-run the
generator after changing dependencies. The generator fails if a new package enters the
shipped dependency graph (`src/Nuvio.Desktop`, transitive) without a curated license, so
this table never carries an unresolved placeholder; every row names a concrete license.

"Bundled" means the component ships inside the release artifact. The app is published
`--self-contained` per RID, so the .NET runtime and the Avalonia/Skia/SQLite native
assets for the target RID are bundled. mpv/libmpv is **not** bundled — see
[`native-dependency-provenance.md`](native-dependency-provenance.md).

| Dependency | Purpose | License | Bundled | Source / Notes |
|---|---|---|---|---|
| .NET runtime (`Microsoft.NETCore.App`) | application runtime | MIT | yes | https://github.com/dotnet/runtime — self-contained per-RID publish |
| Avalonia (`Avalonia.*`, incl. Desktop/Skia/Native/Win32/X11/FreeDesktop/HarfBuzz/Remote.Protocol/BuildServices) | desktop UI framework | MIT | yes | https://github.com/AvaloniaUI/Avalonia — bundled ANGLE natives (`Avalonia.Angle.Windows.Natives`) are BSD-3-Clause |
| Inter (font, via `Avalonia.Fonts.Inter`) | bundled UI font | SIL OFL 1.1 | yes | https://github.com/rsms/inter |
| SkiaSharp (`SkiaSharp`, `SkiaSharp.NativeAssets.*`) | 2D rendering backend (Avalonia.Skia) | MIT | yes | https://github.com/mono/SkiaSharp — native Skia engine is BSD-3-Clause |
| HarfBuzzSharp (`HarfBuzzSharp`, `HarfBuzzSharp.NativeAssets.*`) | text shaping | MIT | yes | https://github.com/mono/SkiaSharp |
| MicroCom.Runtime | COM interop runtime used by Avalonia | MIT | yes | https://github.com/AvaloniaUI/MicroCom |
| CommunityToolkit.Mvvm | MVVM helpers | MIT | yes | https://github.com/CommunityToolkit/dotnet |
| Microsoft.Data.Sqlite (`.Core`) | SQLite ADO.NET provider | MIT | yes | https://github.com/dotnet/efcore |
| SQLitePCLRaw (`SQLitePCLRaw.*`) | native SQLite bindings (`e_sqlite3`) | Apache-2.0 | yes | https://github.com/ericsink/SQLitePCL.raw — the bundled SQLite engine itself is public domain |
| Microsoft.Extensions.* (`DependencyInjection.Abstractions`, `Logging.Abstractions`) | abstractions pulled in by dependencies | MIT | yes | https://github.com/dotnet/runtime |
| Microsoft.IO.RecyclableMemoryStream | pooled memory streams | MIT | yes | https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream |
| Tmds.DBus.Protocol | Linux D-Bus integration (Avalonia.FreeDesktop) | MIT | yes | https://github.com/tmds/Tmds.DBus |
| AvaloniaUI.DiagnosticsSupport | developer diagnostics overlay | MIT | no | https://github.com/AvaloniaUI/Avalonia — Debug-only; excluded from Release artifacts |
| mpv / libmpv | playback backend | GPL-2.0-or-later / LGPL-2.1-or-later | no | External: discovered and launched, never bundled. See `native-dependency-provenance.md` |
| MPV Manager | optional setup helper | MIT per upstream site | no | Documented only; not launched, bundled, or trusted as a playback executable |

## Source availability

GPL source-availability obligations for these binaries are satisfied by the written
offer and source tarball described in [`source-availability.md`](source-availability.md).
'@

Set-Content -LiteralPath $out -Value $content -Encoding utf8
Write-Host "Wrote $out"
if (Select-String -LiteralPath $out -Pattern 'TBD' -Quiet) {
    throw 'generate-license-inventory: TBD found in generated inventory.'
}
Write-Host 'No TBD rows remain.'
